FROM node:18 AS build-stage
WORKDIR /app
RUN apt-get update && apt-get install -y git

# CLONE YOUR FRONTEND REPO
RUN git clone https://github.com/MSVVSSAINADH/docker_hms_frontend.git .
RUN npm install
RUN npm run build

FROM nginx:alpine
# Copy the built React app
COPY --from=build-stage /app/dist /usr/share/nginx/html

# COPY THE MAGIC CONFIG FILE
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]